spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nexapay_promotion?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0
        # 例如: https://your-bucket.oss-cn-beijing.aliyuncs.com
  mail:
    host: smtp.qq.com
    name: nexapay
    port: 465
    username: 87090187@qq.com
    password: tmozobmditoibjbi
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  secret: d6uUmNuE7kYpG5jW8vF3qH9nM2cX4tA5rB1sL7zQ9wK # 至少32个字符的密钥
  expiration: 86400000 # 24小时的毫秒数

aliyun:
    oss:
      endpoint: oss-cn-shanghai.aliyuncs.com           # 例如: http://oss-cn-beijing.aliyuncs.com
      access-key-id: LTAI5tGNZPgxQyrZcijb8wd6     # 您的AccessKeyId
      access-key-secret: 0j7Lo6QfA0MBXK0s7wl0DYdWHjszez  # 您的AccessKeySecret
      bucket-name: qhmall-product        # 您的存储桶名称
      url-prefix: https://qhmall-product.oss-cn-shanghai.aliyuncs.com