spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nexapay_promotion?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  mail:
    host: smtp.qq.com
    name: nexapay
    port: 465
    username: 87090187@qq.com
    password: vymvyzlwkmjibide
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

